### ISSUE TITLE
Typing error in documentation

### ISSUE THREAD

**Issue by albert-github** [mathjax/MathJax-website#43]
A very minor issue
On the page: http://mathjax.readthedocs.org/en/latest/tex.html
it reads:
A function that rells MathJax what ID to use as an anchor for the equation (so that it can be used in URL references).
this should be:
A function that tells MathJax what ID to use as an anchor for the equation (so that it can be used in URL references).

i.e. rells -> tells

**Comment by pkra** [comment]
Thanks for reporting. I think you mean http://mathjax.readthedocs.org/en/latest/options/TeX.html.

 A fix is ready in the 2.6 documentation (http://docs.mathjax.org/en/v2.6-latest/options/TeX.html) and will be merged into `latest` later. FYI the repository for our documentation is https://github.com/mathjax/MathJax-docs.
