### ISSUE TITLE
section id=supporters missing class=row [was "Supporters" heading misaligned ]

### ISSUE THREAD

**Issue by normalhuman** [mathjax/MathJax-website#48]
On the [front page](https://www.mathjax.org/), the "Supporters" heading is not aligned with the rest of them. Screenshot from Chrome 47 (Windows).

![Screenshot](https://cloud.githubusercontent.com/assets/13082030/12538942/f37526e4-c2b4-11e5-9470-c1d24d4b8f5d.PNG)

**Comment by pkra** [comment]
Thanks for the report! This is a regression; the class should include `row`. 

However, this has repercussions for the image grid that we'll have to look that before fixing this.

**Comment by pkra** [comment]
To clarify, some sponsor logos will extend outside the section container if we add `row`; this needs to be fixed.
