### ISSUE TITLE
Scaling demo sets wrong amount of space

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax-website#49]
The rescaling accessibility demo is broken in several ways.  
- As reported [here](https://groups.google.com/d/msg/mathjax-dev/WG4OacQc3D0/_Cz25hq9AQAJ),  the space for the demo isn't correct.  This seems to affect all output modes.
- The fast preview should be turned off (it make the scaled math flicker)
- Scaling should block until the previous typesetting is complete (so you don't get a whole slew of retype sets after you stop moving the slider).

**Comment by dpvc** [comment]
I suspect that the problem is [these lines](https://github.com/mathjax/MathJax-website/blob/gh-pages/js/frontpage.js#L152-L155), inserted to fix the jitter.  First of all, this relies on the output being HTML-CSS (since `.MathJax_Display` is only used for HTML-CSS output), and it should not be necessary of you disable fast-preview, and throttle typesets during slider activity.

**Comment by dpvc** [comment]
Note also that [line 170](https://github.com/mathjax/MathJax-website/blob/gh-pages/js/frontpage.js#L170) probably isn't needed (it is left over from Christian's page, which allowed you to pass the TeX code in the URL, but that makes no sense with this popup window).

Also, [line 151](https://github.com/mathjax/MathJax-website/blob/gh-pages/js/frontpage.js#L151) could just be

```
MathJax.Hub.Queue(['Reprocess', MathJax.Hub, 'output']);
```

since `Reprocess()` will look up the elements if an ID is passed.

**Comment by pkra** [comment]
Thanks! I have to push a couple of fixes; hopefully later this week.
