### ISSUE TITLE
Launch tasks

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-website#5]
- [x] add CNAME file
- [x] update url/baseurl in `_config.yml`

**Comment by pkra** [comment]
- Add CNAME file
- update url/baseurl in `_config.yml`

**Comment by christianp** [comment]
Now with added GitHub task checkboxes!
- [ ] add CNAME file
- [ ] update url/baseurl in `_config.yml`

**Comment by pkra** [comment]
Thanks. Added them to the OP.

**Comment by pkra** [comment]
Fixed by 9c274fffc58a4f0d5dc5baad923dfc642756a28e
