### ISSUE TITLE
docs.mathjax.org seems to be missing

### ISSUE THREAD

**Issue by silverbacknet** [mathjax/MathJax-website#55]
Any link to docs.mathjax.org gives a 404, even though the home page refers to it several times. Except that http://docs.mathjax.org/ itself with redirect to http://docs.mathjax.org/en/latest/ (which is a 404).

**Comment by pkra** [comment]
Thanks for reporting this! It should be fixed now. (Somehow readthedocs lost our subdomain setup).

**Comment by pkra** [comment]
FWIW, I've also filed https://github.com/rtfd/readthedocs.org/issues/2063 to inquire if something is wrong in our setup.
