### ISSUE TITLE
Add information on HTML and character escaping to Live Demo

### ISSUE THREAD

**Issue by paweldudek** [mathjax/MathJax-website#61]
It would be nice to have some sort of a short information on what you can input to Live Demo text view. 

Specifically text that goes in there will be treated as pure HTML and any MathJax formula with unescaped characters entered there won't render. 

This issue comes directly from https://github.com/mathjax/MathJax/issues/1518

**Comment by dpvc** [comment]
I have included some verbiage to indicate that the text you type is HTML and you need to handle special characters carefully.

Sorry this took so long to get completed!

**Comment by paweldudek** [comment]
Haha, no worries! Keep up the great work! 🚀
