### ISSUE TITLE
[frontpage] CDN snippet still points to MathJax CDN

### ISSUE THREAD

**Issue by liffiton** [mathjax/MathJax-website#69]
The "copy this snippet" popup contains:
```
<script src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'></script>
```

With the MathJax CDN shutting down, this probably should be switched to another URL or otherwise modified.

**Comment by pkra** [comment]
Thanks for pointing that out!
