### ISSUE TITLE
Bad HTML and rendering errors on various news items

### ISSUE THREAD

**Issue by fingolfin** [mathjax/MathJax-website#70]
Various news items sport invalid HTML in the author meta tag, leading to rendering errors, as in the attached screen shot. The cause of this is incorrect / missing quoting (double quotes are nested incorrectly)

Two examples where this happens:
* <https://www.mathjax.org/mathjax-v2-7-now-available/> 
* <https://www.mathjax.org/atypon-continues-as-mathjax-supporter-4/>

![screen shot 2017-04-12 at 10 28 22](https://cloud.githubusercontent.com/assets/241512/24948536/eb21157a-1f6a-11e7-991c-1ba84f257205.png)

**Comment by pkra** [comment]
Yes, I'm looking into it. I'm guessing an upstream jekyll change in gh-pages.

**Comment by pkra** [comment]
I suspect this is the right upstream bug: https://github.com/jekyll/jekyll-seo-tag/issues/186
