### ISSUE TITLE
fix errors and warnings from webaim survey

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-website#86]
This is fairly cool: https://webaim.org/projects/million/lookup?homepage=mathjax.org

The error and warnings (cf. http://wave.webaim.org/report#/mathjax.org) should be easy to fix.

**Comment by dpvc** [comment]
Finally got the chance to fix this, while I was doing some other updates.  Thanks for the interesting link.  I had no idea that MathJax was ranked so high!
