### ISSUE TITLE
Removal of realtime update considered a regression

### ISSUE THREAD

**Issue by paulcarey** [mathjax/MathJax-website#88]
Hi
The realtime update that rendered equations as they were typed was very useful, providing instant feedback on whether math syntax was right or wrong. The change in behaviour from realtime update, to manually requiring a user click 'Render HTML' is, in my opinion, a regression that should be reverted. It slows the feedback loop and makes the UX more awkward.
Thanks for considering.

**Comment by dpvc** [comment]
Sorry for the long delay in getting to this.  The demo has been updated to include live refresh (the button is still in place for older browsers).
